package Model;
// Generated 25-09-2014 12:03:49 by Hibernate Tools 3.6.0



/**
 * School generated by hbm2java
 */
public class School  implements java.io.Serializable {


     private int schoolId;
     private String schoolName;
     private String schoolAddress;
     private String schoolEmail;
     private String schoolPhone;
     private String schoolEducationLines;

    public School() {
    }

	
    public School(int schoolId) {
        this.schoolId = schoolId;
    }
    public School(int schoolId, String schoolName, String schoolAddress, String schoolEmail, String schoolPhone, String schoolEducationLines) {
       this.schoolId = schoolId;
       this.schoolName = schoolName;
       this.schoolAddress = schoolAddress;
       this.schoolEmail = schoolEmail;
       this.schoolPhone = schoolPhone;
       this.schoolEducationLines = schoolEducationLines;
    }
   
    public int getSchoolId() {
        return this.schoolId;
    }
    
    public void setSchoolId(int schoolId) {
        this.schoolId = schoolId;
    }
    public String getSchoolName() {
        return this.schoolName;
    }
    
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }
    public String getSchoolAddress() {
        return this.schoolAddress;
    }
    
    public void setSchoolAddress(String schoolAddress) {
        this.schoolAddress = schoolAddress;
    }
    public String getSchoolEmail() {
        return this.schoolEmail;
    }
    
    public void setSchoolEmail(String schoolEmail) {
        this.schoolEmail = schoolEmail;
    }
    public String getSchoolPhone() {
        return this.schoolPhone;
    }
    
    public void setSchoolPhone(String schoolPhone) {
        this.schoolPhone = schoolPhone;
    }
    public String getSchoolEducationLines() {
        return this.schoolEducationLines;
    }
    
    public void setSchoolEducationLines(String schoolEducationLines) {
        this.schoolEducationLines = schoolEducationLines;
    }




}


